-- "C##MBC".PROFESSOR definition

CREATE TABLE "C##MBC"."PROFESSOR" 
   (	"PROF_ID" VARCHAR2(10), 
	"RESIDENT_ID" VARCHAR2(14) NOT NULL ENABLE, 
	"NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"DEPT_ID" VARCHAR2(10), 
	"POSITION" VARCHAR2(10), 
	"YEAR_EMP" NUMBER(4,0), 
	 CONSTRAINT "PK_PROFESSOR" PRIMARY KEY ("PROF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PROFESSOR" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "C##MBC"."DEPARTMENT" ("DEPT_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;